### PR TITLE
[WIP] Use oracle ORDER in txn.id sequence

### PR DESCRIPTION
**Pull request by AbdealiLoKo**

### CODE REVIEW

**Comment by AbdealiLoKo** [comment]
Blocked by https://github.com/sqlalchemy/sqlalchemy/issues/10207

**Comment by CaselIT** [comment]
supporting both 1.4 and 2.0 will be a bit of cumbersome, but you can check if sequence is a subclass of `DialectKWArgs` and use order or oracle_order

**Comment by indiVar0508** [comment]
are we planning to include this for next minor release?

**Comment by AbdealiLoKo** [comment]
Not sure if you want to spend time on this as supporting it in both sqlalchemy 1.4 and 2.0 will be somewhat more complicated ?

As per this discussion: https://github.com/sqlalchemy/sqlalchemy/discussions/10023#discussioncomment-6293623
Sqlalchemy 1.4.x will be EOL once 2.1 is released. And 2.1 is currently in development with no specific ETA

**Review by indiVar0508 — APPROVED** [review]

**Pull request merged**
